### ISSUE TITLE
(sorry) Thanks for removing EchoPet without warning :(

### ISSUE THREAD

**Issue by TNTUP** [Borlea/ArmorEquipEvent#10]
Hi Borlea, I'm not sure why you abondoned EchoPet fork you did, now I'm stuck on the 1.11.2 version, if the 1.12 comes out and gets broken in 1.12, I'm dead because I have players who bought pet packs I did on my server store and it would be nice to allow posting on your profile, everyone who wants the EchoPet plugin for 1.11.2 or lower, is dead.

Its a shame to see it go EchoPet without warning on SPigot, GitHub and your CI aswell. I counted on you for latest updates. So I'm stuck on 1.11.2 for now, until 1.12 comes out (maybe in months). A snapshot got out yesterday so I guess we have 1-2 month left on 1.11.2, or else ill be forced to remove EchoPet and everyone who bought 'em I'll be forced to refund them :/

I'm sorry if I've opened an issue which does not relate to AEE (ArmorEquipEvent) but that was the only source of communication I can start with you, I want news or if you can retry working on EchoPet, even I can donate if it can motivate you.... My server depend on EchoPet since 1.10. Thanks, have a nice day =(

PS: Don't delete this issue please, I want some news why you removed EchoPet without warning, and let someone fork it for you... I hope if you can update EchoPet if any issues arise. 

PSS: Mind if you can send me the entire source of your EchoPEt you did? If I do decompilation, that can be worse (not the same code in case) that'll be appreciated :D You was the best EchoPet fork-er you did when I helped you fixing issues

**Comment by Borlea** [comment]
Pretty much restating stuff here https://github.com/Borlea/ArmorEquipEvent/issues/8
I deleted it to force people to switch to a better pet plugin.
If I come back to mc(which is possible, but probably not until atleast 1.13)I'm gonna rewrite EchoPet under sponge because spigot is meh.
I gave my old network owner all the files required to build it, and again has been notified. If he wants to get in contact with you(about possibly giving, or selling) its his option and not mine.

**Comment by TNTUP** [comment]
Ah shame to see it go then :( There's no such better pet plugin than yours. I'm aware of SonarPet, but seems not updated to 1.11.2 or bugfixes which are fixed by your plugin.

If you come back to 1.13, I'll be forced to stop using EchoPet plugin because there's no known pet plugins (unless SonarPet works in 1.11, has new mobs or updating regularly) I hope for 1.13 then ill switch to yours then. I'm never going to switch to Sponge, every plugin I use isn't on Sponge yet and It'll force me to reset my entire server... so no me Sponge... 

Well, I hope he can give me his build (updated one) or the source (I don't code java, if he allows me to publish on github and let other fork it (and crediting DSH, you and your old server owner guy). If he does sell at a higher price which I can't afford, I'll be forced to notify my players that the Pet plugin is discontinued, and refund if necessary :(

Though, Thanks again for your work you did for 1.11.2. I'll close the issue since you answered me, and awaiting response from your old network owner (if he wants to give it or pay for it (if he sees it :P))

Have a nice day Borlea. Have a nice day :)

**Comment by andrewkm** [comment]
I'm already updating it lol, just get in touch. ;)

**Comment by Borlea** [comment]
@andrewkm If you're updating EchoPet I suggest quiting while ahead. Huge waste of time when something can be done easier and better.

**Comment by andrewkm** [comment]
No thanks. Long done. Works great.

**Comment by TNTUP** [comment]
Just telling, EchoPet dead in 1.12, forcing me to force players stopping using it even they paid for it. Guess time for me to end my server which is soon 4 years running, better at 5 years and i'll be out :(

**Comment by andrewkm** [comment]
@TNTUP just contact me, I've already updated long ago and re-written the entire thing.

**Comment by TNTUP** [comment]
@andrewkm Last time I've contacted you I had to pay, but the price I've not asked how much. Since then I kept the last build I had. I'll contact you privately

**Comment by andrewkm** [comment]
@tntup of course you have to pay, what you think this is, a giveaway? lmao.

**Comment by TNTUP** [comment]
Expected to pay for it, I'm aware of it.

**Comment by Borlea** [comment]
Is andrew still being a giant meme over here

**Comment by TNTUP** [comment]
@Borlea Well, what he requested to me is too expensive. My server is locked to 1.11.2 forever until it gets unsupported :(

**Comment by andrewkm** [comment]
is borlea still being completely irrelevant over here lol

**Comment by Borlea** [comment]
@TNTUP gimme a few days or something and I'll have a prototype for this 1.12 prerelease thing.

**Comment by Borlea** [comment]
Decided to go out of my way to add parrots off the bat.. [cute af ](http://i.imgur.com/sj6uiMV.png)

**Comment by TNTUP** [comment]
@Borlea omg you're gonna be a life saver, but keep it private :/ Anyways my server cannot pass to 1.12 due to Stats2, Vote, Horses, Payday. Thanks anyway Borlea

**Comment by i9hdkill** [comment]
@Borlea Back for 1.12? That would be great! We would be happy if you put it back to git, so we can play around with it. Probably also codewise!:)

**Comment by Borlea** [comment]
@i9hdkill https://github.com/Borlea/EchoPet

**Comment by i9hdkill** [comment]
Thanks! <3

**Comment by remymine** [comment]
You sir, are the best, thanks for supporting the community @Borlea 

Shame on @andrewkm

**Comment by andrewkm** [comment]
@remymine If you want anything from my team get your wallet out kid. Welcome to the real world. Not an ounce of shame what so ever.

**Comment by remymine** [comment]
Asking 200$ for an open source resource based plugin. Not a chance mate, not when kind people from the community will take matter into own hands and fork it for free. 
Anyhow, bought hundreds of plugins altogether, so I don't know who you are reffering to. Probably just wanna prove who has the biggest e-dick.

**Comment by andrewkm** [comment]
*autism intensifies*

**Comment by TNTUP** [comment]
@remymine It was the  same price he offered me and I can't even afford that amount. I'm canadian so it would be way more expensive, and he owns a blacklisted server (Correct me if im wrong). AGP Management, bad company from my opinion.

@Borlea Please lock this issue. Since you've taken back EchoPet, this issue is closed.

**Comment by Borlea** [comment]
Can't prevent commenting, can only delete stupidity.

**Comment by TNTUP** [comment]
@Borlea Mind deleting it then? Would be appreciated to prevent insults here

**Comment by andrewkm** [comment]
@borlea I agree. We should delete this ASAP! Wouldn't want anyone to get offended by all the harsh AF insults we be tossin around, right @TNTUP lmao.
