### ISSUE TITLE
Event not firing when switching armor.

### ISSUE THREAD

**Issue by kicjow** [Borlea/ArmorEquipEvent#4]
Hello, I have been using your plugin in my CrazyEnchantments plugin and its been the best help for me. I have run into a problem where say you have a block in your first slot and then you have a piece of armor on. You then hover over the armor and hit 1 to move it to that slot but the event doesn't fire. I have been trying to make a work around but can't seem to get it working. I would like to ask you if you could try and fix it and make the event fire. Because with my CrazyEnchantments plugin the potion effects stay even when removing the armor using this method.

![armor bug](https://cloud.githubusercontent.com/assets/5057118/18889017/edd747ea-84c8-11e6-8748-1278ea697364.gif)

**Comment by Borlea** [comment]
In your gif you have a grass in the first slot, when you press 1 in unequip the chestplate, the chestplate goes to 1 but you grass gets shifted down a slot.. That isn't vanilla like.

**Comment by kicjow** [comment]
Strange. I didn't know that. I'll look into it. Thanks for the reply and I'll get back to you with what I find

**Comment by kicjow** [comment]
Hello, so I was trying out what you said so I jumped on to a single player world and it still did it.

**Comment by Borlea** [comment]
Doesn't work on 1.10.2

**Comment by kicjow** [comment]
I am on 1.8.8 maybe try that?

**Comment by Borlea** [comment]
Seems to work on 1.8.

Due to being something that only exists in an old version I wont be doing any fix to support something that no longer exists in 1.9.2+(from testing)

**Comment by kicjow** [comment]
Thanks ill make sure to mention that to people that use my plugin.
