### ISSUE TITLE
Echopet

### ISSUE THREAD

**Issue by andrewkm** [Borlea/ArmorEquipEvent#9]
No offence dude but you jumping ship deleting source like this is bullshit

I have three developer depbfuscating it now and rewriting it completely and will be selling it at $199.99 per network interested.

Should you feel the need to take legal action I will gladly provide my lawful representation to you. See ya. I gave you a chance but as it seems you give no shit our team will be updating and selling this for profit ourselves.

Happy new year. See ya.

**Comment by Borlea** [comment]
Well okay sir. You do whatever you want
